project:
  type: website
  output-dir: docs

website:
  title: "magasinet"
  site-url: https://terningkast.net
  resources:
    - CNAME

  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: pandoc
    css: styles.css
    toc: true



