project:
  type: website
  output-dir: docs

website:
  title: "magasinet"
  site-url: https://terningkast.net
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    resources:
      - CNAME

format:
  html:
    theme: pandoc
    css: styles.css
    toc: true



